// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TG.ECommerce.Product.API.Infrastructure;

namespace TG.ECommerce.Product.API.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    partial class ECommerceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TG.ECommerce.Product.API.Models.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Spor"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Giyim"
                        });
                });

            modelBuilder.Entity("TG.ECommerce.Product.API.Models.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "741c92eb-9b98-4e36-8513-be41e3f50c8a",
                            CategoryId = "1",
                            CreatedTime = new DateTime(2023, 4, 3, 14, 27, 16, 790, DateTimeKind.Local).AddTicks(1802),
                            Description = "32 GB RAM oyun bilgisayarı",
                            Name = "Bilgisayar",
                            Price = 1000m
                        },
                        new
                        {
                            Id = "dfad4c50-ca31-45f6-b99b-321bec556bd9",
                            CategoryId = "1",
                            CreatedTime = new DateTime(2023, 4, 3, 14, 27, 16, 791, DateTimeKind.Local).AddTicks(1966),
                            Description = "Temiz kullanışlı tablet",
                            Name = "Tablet",
                            Price = 500m
                        },
                        new
                        {
                            Id = "bea9036e-2da4-4a94-a3ac-c74b3725cc7a",
                            CategoryId = "2",
                            CreatedTime = new DateTime(2023, 4, 3, 14, 27, 16, 791, DateTimeKind.Local).AddTicks(1980),
                            Description = "İkinci el koşu bandı",
                            Name = "Koşu Bandı",
                            Price = 2000m
                        });
                });

            modelBuilder.Entity("TG.ECommerce.Product.API.Models.Entities.Product", b =>
                {
                    b.HasOne("TG.ECommerce.Product.API.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TG.ECommerce.Product.API.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
